### ISSUE TITLE
Project page update

### ISSUE THREAD

**Issue by angeraz** [ten-o-seven/ten-o-seven.github.io#8]
MS app redlines available in Figma.

**Comment by angeraz** [comment]
- [x] [alignment issue](https://www.figma.com/design/xggasuik9kLMPWDSzAbWGX?node-id=647-4099#829594275)
- [x] background section - [bounding box](https://www.figma.com/design/xggasuik9kLMPWDSzAbWGX?node-id=647-4099#829596041) UI update
- [ ] [line weight](https://www.figma.com/design/xggasuik9kLMPWDSzAbWGX?node-id=647-4099#803225234) difference
- [x] [typo](https://www.figma.com/design/xggasuik9kLMPWDSzAbWGX?node-id=647-4099#829602430)

**Comment by cchen9299** [comment]
lineweight difference is because the asset is scaled up. export on your end, specify the dimension to use it at and give me the assets if you want higher control.
