### ISSUE TITLE
Site content update

### ISSUE THREAD

**Issue by angeraz** [ten-o-seven/ten-o-seven.github.io#9]
DSLR, doodles, and just for fun page assets are available on google drive. See figma for comments on design instructions.

**Comment by angeraz** [comment]
Just for fun page fix
- [x] VIP card for pp has a broken image link when clicked on the left arrow.
- [x] please show cards in the following sequence: 1. bilin (preloaded, default), 2. haojie, 3. albie
- [ ] Aditi money image is blurry

**Comment by cchen9299** [comment]
you have to define "blurry" better maybe with a screenshot of what you're seeing. the asset is grabbed directly from the folder
